// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {fs} from '../models';

export function GetAppConfig():Promise<config.ApplicationConfig>;

export function ReadFolder(arg1:string):Promise<fs.Folder>;
