// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function ReadFolder(arg1) {
  return window['go']['main']['App']['ReadFolder'](arg1);
}
